name: Deploy to Render

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Trigger Render Deployment
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          # Define the Render API endpoint and service ID
          SERVICE_ID=srv-cst2lrrtq21c73a6mi5g # Replace this with your actual Service ID
          RENDER_API_URL="https://api.render.com/v1/services/srv-cst2lrrtq21c73a6mi5g/deploys"

          # Trigger the deployment using Render's API
          curl -X POST \
            -H "Accept: application/json" \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            $RENDER_API_URL